#include "nrfx_config.h"

#define APP_SCHEDULER_ENABLED 1
#define APP_TIMER_ENABLED 1

#define APP_FIFO_ENABLED 1

#define APP_UART_DRIVER_INSTANCE 0
#define APP_UART_ENABLED 1

#define BUTTON_ENABLED 1
#define CLOCK_ENABLED 1

#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define GPIOTE_ENABLED 1

#define BLE_ADVERTISING_ENABLED 1
#define BLE_NUS_ENABLED 1
#define BSP_BTN_BLE_ENABLED 1

#ifdef DEBUG
#define NRF_LOG_ENABLED 1
#endif

#define UART_ENABLED 1
#define UART0_ENABLED 1

#define NRF_PWR_MGMT_ENABLED 1
#define NRF_PWR_MGMT_CONFIG_FPU_SUPPORT_ENABLED 1

#define NRF_FSTORAGE_ENABLED 1

#define NRF_SDH_ENABLED 1
#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_BLE_GAP_DATA_LENGTH 251
#define NRF_SDH_BLE_GATT_MAX_MTU_SIZE 247
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 5
#define NRF_SDH_BLE_VS_UUID_COUNT 1
#define NRF_SDH_SOC_ENABLED 1

// #define RETARGET_ENABLED 1

// Maybe not needed?
#define NRF_BLE_GATT_ENABLED 1
