#define NRFX_PRS_ENABLED 1
#define NRFX_PRS_BOX_0_ENABLED 0
#define NRFX_PRS_BOX_1_ENABLED 0
#define NRFX_PRS_BOX_2_ENABLED 0
#define NRFX_PRS_BOX_3_ENABLED 0
#define NRFX_PRS_BOX_4_ENABLED 1
#define NRFX_PRS_CONFIG_DEBUG_COLOR 0
#define NRFX_PRS_CONFIG_INFO_COLOR 0
#define NRFX_PRS_CONFIG_LOG_ENABLED 0
#define NRFX_PRS_CONFIG_LOG_LEVEL 3

#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_IRQ_PRIORITY 7

#define NRFX_GPIOTE_ENABLED 1

#define NRFX_UARTE_ENABLED 1
#define NRFX_UARTE0_ENABLED 1

#define NRFX_UART_ENABLED 1
#define NRFX_UART0_ENABLED 1

#define NRFX_PPI_ENABLED 1

